name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        ./Tools/add_plugin_filed_to_preference.sh
        defaults read com.apple.dt.Xcode
    - run: make
